### ISSUE TITLE
NavBar TODO

### ISSUE THREAD

**Issue by gwonhong** [gwonhong/skku-art-exhibition#2]
- [ ] 하단 공란 제거
- [ ] scroll bar 위치 수정 (브라우저마다 다르게 보이므로 확인 필요)
- [ ] 작가명 우측 정렬
